Entity/FeedbackInterface.php
<?php

namespace Megacoders\FeedbackModuleBundle\Entity;

interface FeedbackInterface {

    /**
     * @return \DateTime
     */
    public function getDate();

    /**
     * @return string
     */
    public function getName();

    /**
     * @return string
     */
    public function getEmail();

    /**
     * @return string
     */
    public function getMessage();

}

Resources/views/done.html.twig
<h1 class="text-center">
    <i class="fa fa-check-circle-o"></i>
</h1>
<h2 class="text-center">{{ 'modules.feedback.messages.done_title'|trans }}</h2>
<h3 class="text-center">{{ 'modules.feedback.messages.done_description'|trans }}</h3>

Resources/views/index.html.twig
{% extends 'MegacodersPageBundle:Module:base.html.twig' %}

{% block css_class %}module-wrapper_feedback{% endblock %}

{% block content %}
    {{ form_start(form) }}
    {{ form_widget(form) }}
    <input type="submit" value="{{ 'modules.feedback.entities.feedback.actions.send'|trans }}"/>
    {{ form_end(form) }}
{% endblock %}

Resources/views/notification.html.twig
<h3>{{ 'modules.feedback.mail.subject'|trans }}</h3>

<table>
    <tr>
        <th style="padding-right:10px;vertical-align:top;text-align:left;">{{ 'admin.entities.feedback.date'|trans }}</th>
        <td>{{ feedback.date|date('j F Y, H:i') }}</td>
    </tr>
    <tr>
        <th style="padding-right:10px;vertical-align: top;text-align: left;">{{ 'admin.entities.feedback.name'|trans }}</th>
        <td>{{ feedback.name }}</td>
    </tr>
    <tr>
        <th style="padding-right:10px;vertical-align: top;text-align: left;">{{ 'admin.entities.feedback.email'|trans }}</th>
        <td>{{ feedback.email }}</td>
    </tr>
    <tr>
        <th style="padding-right:10px;vertical-align: top;text-align: left;">{{ 'admin.entities.feedback.message'|trans }}</th>
        <td>{{ feedback.message }}</td>
    </tr>
</table>